### PR TITLE
Revert "Add: Banjo, Terry, Byleth, Magnamalo, Palamute, and Palico"

### PR DESCRIPTION
**Pull request by N3evin**
Reverts N3evin/AmiiboAPI#59

### CODE REVIEW

**Comment by N3evin** [comment]
Revert the pull request, as it wasn't testing. Giving error. @DanTheMan827

**Comment by DanTheMan827** [comment]
Yeah, I also have two different sets of IDs for the smash ones...

**Comment by N3evin** [comment]
> Yeah, I also have two different sets of IDs for the smash ones...

that's weird. Are they verified? Like with the amiibo?

**Comment by DanTheMan827** [comment]
They're what other people have provided, so I can't say I scanned them myself

**Comment by N3evin** [comment]
I Will have to check with @cheatfreak47. But for now, I will revert it.

**Comment by DanTheMan827** [comment]
That would be different...

Although, someone looking to spoof would only have to spoof the first 2 bytes, not the entire ID...

They might both be valid for all we know.

**Comment by N3evin** [comment]
> They might both be valid for all we know.

Yeah, but if that's the case, we might have to add both into the database. I will hold it off and double-check with cheat. Furthermore, did u never the code right? Because it's obviously throwing error.

**Comment by DanTheMan827** [comment]
I didn't change any of the code.

I also ran it through a validator script I wrote (albeit not quite finished)

Maybe it would be worthwhile to add it along with a github task that runs it and any other test scripts you might have

https://github.com/DanTheMan827/AmiiboAPI/blob/database-validation/checkdatabase.py

**Comment by N3evin** [comment]
> I didn't change any of the code.
> 
> I also ran it through a validator script I wrote (albeit not quite finished)
> 
> Maybe it would be worthwhile to add it along with a github task that runs it and any other test scripts you might have
> 
> https://github.com/DanTheMan827/AmiiboAPI/blob/database-validation/checkdatabase.py
> 
> I also ran it through a json linter and no errors... maybe it crashes when there isn't corresponding game info present?

Yup, it was due to the game info. I will make an update with the 3 SSB amiibo only then. Added an empty game_info for them for now.

```
3b40000003a30002 - Banjo
3c80000003a40002 - Terry
210b000003a50002 - Byleth
```

I also believe that the one with the 23d is a spoof. The one from MHR, I will ignore till we get more solid evidence that the id is correct. Was trying to avoiding adding spoof. See if you can dig out more info?

**Comment by DanTheMan827** [comment]
It's weird, according to the 3dbrew wiki, it's the "model number" that's different between the two sets.

**Comment by N3evin** [comment]
> It's weird, according to the 3dbrew wiki, it's the "model number" that's different between the two sets.

But that's weird. Unless they really added that in at this stage. We can just add them in at the end of the day if it's really true.

**Comment by N3evin** [comment]
Are we able to confirm that they finally had the same amiibo but a different mode number? Are the both set from different region?

**Comment by DanTheMan827** [comment]
not yet... as for the MHR one, maybe it's different for the special edition one

**Comment by N3evin** [comment]
Alright, as of now, let's wait for a day. Maybe will see how it goes. From your database checker. Seems like you also working it for game_info too as I noticed the variable is declared but not use.

Would be available? Will be great if the validator could also pull the request to the repo. That is awesome work.

**Comment by N3evin** [comment]
At the same time have to check with @MrKev312 for his updated game_info.json. Or the scraper he had, to work out how to get it.

**Comment by DanTheMan827** [comment]
yeah, I plan on implementing the game_info checks too.

if it had had those checks, it would have definitely failed the check

**Comment by N3evin** [comment]
> if it had had those checks, it would have definitely failed the check

All good, thanks for the awesome validator. I will add the MHR, just did a cross-check with another dude.

**Comment by DanTheMan827** [comment]
I might also make a script that grabs the ID from a dump and prompts you for its info to add into the database, but python formats a little differently (and sorts by key values)

**Comment by MrKev312** [comment]
Here's [the script](https://github.com/N3evin/AmiiboAPI/files/6214581/Amiibo.zip) that I made to scrap the info, it takes in the json that the [API generates](https://amiiboapi.com/api/amiibo/) as amiibo.json in the same folder. Then just click to open and it'll generate the games_info.json which can take some time.

**Comment by N3evin** [comment]
> Here's [the script](https://github.com/N3evin/AmiiboAPI/files/6214581/Amiibo.zip) that I made to scrape the info, it takes in the json that the [API generates](https://amiiboapi.com/api/amiibo/) as amiibo.json in the same folder. Then just click to open and it'll generate the games_info.json which can take some time.

Seems to be getting null exception when i run it.

**Comment by MrKev312** [comment]
Even when using the amiibo.json provided in the zip? Could I see the error?

**Comment by N3evin** [comment]
> Even when using the amiibo.json provided in the zip? Could I see the error?

ah my bad, seems to not work with the amiibo db we had. I guess the data is the one from api call?

**Comment by MrKev312** [comment]
After looking at the code for the scraper, I remembered that it was a part of the chain of different programs I made to get to the final games_info.json. I'll make an all-in-one version and upload that on GitHub

**Pull request merged**
