### PR TITLE
Splatoon 3 Alterna and Side Order

### PR DESCRIPTION
**Pull request by AbandonedCart**
# Pull request form
### Checklist
 - [X] The ids provided are not spoof.
 - [X] The ids provided are all in lowercase.
 - [X] The `game_info.json` had been updated with the corresponding ids.
 - [X] Images of amiibo had been provided with the highest quality.

### Link to amiibo.life for amiibo
- https://amiibo.life/amiibo/splatoon/callie-alterna
- https://amiibo.life/amiibo/splatoon/marie-alterna
- https://amiibo.life/amiibo/splatoon/pearl-side-order
- https://amiibo.life/amiibo/splatoon/marina-side-order

See #181
Running the game-info generator returned `429 Too many requests` so they are blank

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Give me one minute to get better images

**Comment by N3evin** [comment]
> Let me know if you prefer ` - Side Order` formatting instead and I’ll change it.

It should be fine for now.

Do you mind PR to dev branch instead of master?

**Comment by AbandonedCart** [comment]
No problem. I forgot to change it when selecting branches.

**Comment by AbandonedCart** [comment]
Sounds good. I got my copy of the generator from the original repo, so I will pull this one and hopefully next time I can spare you the hassle. Thanks!

**Pull request merged**
