### PR TITLE
Add S3 amiibo

### PR DESCRIPTION
**Pull request by TheDrawingCoder-Gamer**
Note: These IDs may not be correct (especially the ffff) part. I have generated amiibo from them, written to tags, and it works as expected.

### CODE REVIEW

**Comment by Brickleberry19** [comment]
the IDs are from spoofed amiibo, which means they are not the same as the original amiibo

**Comment by TheDrawingCoder-Gamer** [comment]
meaning this PR can't be accepted?

**Comment by TheDrawingCoder-Gamer** [comment]
https://github.com/N3evin/AmiiboAPI/pull/95#issuecomment-1094044827 he denies spoof ids - please disregard

**Comment by Brickleberry19** [comment]
The original IDs 
Octoling blue
08050200041B0402

Inkling yellow
0800010004150402

Smallfry
08060100041C0402

**Pull request closed without merging**
