### PR TITLE
Added Sora (Kingdom Hearts)

### PR DESCRIPTION
**Pull request by AbandonedCart**
# Infomation
Please use the following form when doing a pull request for amiibo database. Do update the `amiibo.json` and  `game_info.json` file to prevent error and make sure proper testing had been done. If unsure on `game_info.json` please use the following format attached below and just set the games as empty array, as it will be auto generated. Tick the `checklist` before submitting to ensure you have all the required information.

# Pull request form
### Checklist
 - [x] The ids provided are not spoof.
 - [x] The ids provided are all in lowercase.
 - [x] The `game_info.json` had been updated with the corresponding ids.
 - [x] Images of amiibo had been provided with the highest quality.

See https://github.com/N3evin/AmiiboAPI/issues/162

Apparently GitHub Desktop decided to randomly close the last one.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
For some reason, trying to change branches on my end is closing the pull request

**Comment by AbandonedCart** [comment]
Let's see if I can at least reopen it

**Comment by N3evin** [comment]
I am currently away on a holiday. Will only be back on Monday. Will do it when I'm back.

**Comment by AbandonedCart** [comment]
Sorry for all the spam. I was between computers and nothing wanted to sync. Enjoy your vacation!

**Pull request merged**
