### PR TITLE
Add database info for upcoming SSBU

### PR DESCRIPTION
**Pull request by AbandonedCart**
Apologies if this is not the method to update the database. 

The dates are still pending for all characters, except Min Min. 
There are two new game entries that accompany the characters. 
Final images were only available for two of the characters.
I have not found an ID for Alex yet, but have the image when I do.

Feel free to take parts of the data if it can't be used as a whole.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
The Minecraft one really didn't want to be inside the list, but it should be correct now.

**Comment by N3evin** [comment]
Hi, based on the ID, it doesn't seem to match the regular convention for the bins. They seem to be spoof bins id.

Could anyone else confirm the legitimacy of the ids?

**Comment by AbandonedCart** [comment]
That's entirely likely. In that case, please disregard. I will wait until there is more information.

**Comment by N3evin** [comment]
Thank you for the hardwork. It doesn't have amiibo series in the id :)

**Comment by AbandonedCart** [comment]
Make sense. It looked a bit too generic, but I'm still somewhat new to the format and assumed the IDs were getting lazier. I'll keep watching for a legitimate one.

Thanks for everything you do.

**Pull request closed without merging**
