### PR TITLE
Add Super Mario Cereal

### PR DESCRIPTION
**Pull request by Cabalist**
(Also made whitespace consistent in JSON file)

### CODE REVIEW

**Comment by N3evin** [comment]
Error with characters after adding super mario cereal

**Comment by Bombastisch** [comment]
Noticed it too. The cereal doesn't show up in TagMo.

**Comment by N3evin** [comment]
Yeah. Something wrong with the filters that it even make characters not working.

**Comment by N3evin** [comment]
All good, had been fixed :) Apparently Super Mario Cereal uses another character id.

**Comment by Cabalist** [comment]
Sorry about that!  :/  Thanks for catching it

**Comment by N3evin** [comment]
All good! Thanks for the cleaning up and update. Wasn't able to do it since I'm still away.

**Comment by Bombastisch** [comment]
Can confirm! Shows up now. Thank you for the fix! :)

**Pull request merged**
